### ISSUE TITLE
Running tdparse+ and tdparse models

### ISSUE THREAD

**Issue by kush789** [bluemonk482/tdparse#2]
Hi,

When we execute the script as mentioned in the README, the tdparse+ (m) model gets used. Is there any way we can reproduce the results for the tdparse+ and tdparse models?

Thanks a lot!

**Comment by bwang482** [comment]
Hi @kush789 the difference between tdparse+ (m) and tdparse+ is that tdparse+ doesn't taking into account the same-target-multiple-appearence scenario and only count the first target appearance. In this case you can add a `break` after line 171 `target_positions.append(position)` in utilities.py. 

The result for tdparse+ with `C=0.003` is 

> Macro-F1 score:  0.697672428496
> Accuracy score:  0.721098265896
> Macro-F1 score (2 classes): 0.66014500638

**Comment by bwang482** [comment]
The tdparse model referred in the paper is actually tdparse (m), which doesn't use features from lexicon filtered words. So all you gotta do is commenting out line 407 and 408 from tdparse.py. 

The result for tdparse (m) with `C=0.005` is

> Macro-F1 score:  0.684067992817
> Accuracy score:  0.709537572254
> Macro-F1 score (2 classes): 0.642521908471

**Comment by kush789** [comment]
That helps a lot, thanks! :)
